spring:
  application:
    name: eureka-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://49.235.247.57:11001/eureka/
    instance:
      prefer-ip-address: true #使用ip地址注册
      lease-renewal-interval-in-seconds: 5 #想注册中心发送心跳的续约间隔时间5s
      lease-expiration-duration-in-seconds: 10 #eureka client发送心跳给server端后，续约到期时间（默认90秒）
server:
  port: 13101

